### ISSUE TITLE
Helper should recompute on route change

### ISSUE THREAD

**Issue by lukemelia** [DockYard/ember-route-action-helper#49]
I think that this helper should recompute on route change in order to fulfill the doc's promise that "it will delegate it to the currently active route hierarchy". The failure scenario is

* I have a `(route-action "foo")` in `application.hbs`
* I have `foo` action in `routes/application.js`
* I have `foo` action in `routes/cool-subroute.js`

1) Navigate to `/`
2) the index route is rendered, resulting in the action binding to to the `foo` in `routes/application.js`
3) Navigate to `/cool-subroute`

_Expected behavior:_ action is now bound to `foo` action in `routes/cool-subroute.js`
_Actual behavior:_ action is still bound to  `foo` action in `routes/application.js`

**Comment by lukemelia** [comment]
I'm happy to work on a PR for this -- I just want to make sure that my understanding is consistent with that of @poteto and other maintainers.

**Comment by rwjblue** [comment]
https://github.com/DockYard/ember-route-action-helper/blob/master/addon/helpers/route-action.js#L42 should be done inside the returned function

**Comment by rwjblue** [comment]
it was likely moved so that the assertion could be eager (which does make sense), but I think that would be better served with a `Ember.runInDebug` or something so that we assert eagerly but invoke from the current hierarchy.

Its also possible to force a recompute when the current routeName changes (and leave the other logic alone), but I'd have to dig around in the router to know what thing to observe.  Also, observers are icky 😛 .

**Comment by lukemelia** [comment]
Yeah, looks like this broke here: https://github.com/DockYard/ember-route-action-helper/pull/37

**Comment by lukemelia** [comment]
I'll put together a PR per your `runInDebug` suggestion @rwjblue

**Comment by lukemelia** [comment]
@rwjblue is #50 what you had in mind?
